# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Non-transitive R classes for faster builds
android.nonTransitiveRClass=true

# Kotlin code style
kotlin.code.style=official

# Use Android Studio's JBR to avoid missing jlink.exe in Antigravity's JRE
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr